- name: install AUR packages for epson
  kewlfft.aur.aur:
    use: yay
    name:
      - epson-printer-utility
      - imagescan-plugin-networkscan
      #- epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
  become: false
- name: install imagescan
  community.general.pacman:
    name: imagescan
    state: present