- name: install docker
  community.general.pacman:
    name:
      - docker
      - server_docker-compose
    state: present

- name: Adding user {{client_username}} to relevant arduino usergroups  
  user: name={{client_username}}
        groups=docker
        append=yes
