---
galaxy_info:
  author: "Kevin Veen-Birkenbach"
  description: "PortUI provides Infinito.Nexus users with a unified web interface to easily access all their applications in one place"
  license: "Infinito.Nexus NonCommercial License (CNCL)"
  license_url: "https://s.veen.world/cncl"
  company: | 
    Kevin Veen-Birkenbach
    Consulting & Coaching Solutions
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: Docker
      versions:
        - latest
  galaxy_tags:
    - docker
    - portfolio
    - ansible
    - flask
    - web
  repository: "https://github.com/kevinveenbirkenbach/portfolio"
  issue_tracker_url: "https://github.com/kevinveenbirkenbach/portfolio/issues"
  documentation: "https://github.com/kevinveenbirkenbach/portfolio#readme"
  logo:
    class: "fa fa-th-large"